name: "testworkflows"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build-java:
    runs-on: [self-hosted]
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
      PLATFORM_REPO: 'test-maven-repo'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: http://localhost:8081
        with:
          oidc-provider-name: github-jfrog
          oidc-audience: my-aud
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Publish Build info With JFrog CLI
        run: |
          jf gradle-config --use-wrapper --repo-deploy=test-maven-repo
          jf gradle :subdir:clean :subdir:artifactoryPublish --no-daemon -b ./build.gradle
          jf rt bp
