:name: "testworkflows2"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
    runs-on: [self-hosted]
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
      PLATFORM_REPO: 'generic-local'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Fetch Access Token from Artifactory
          id: fetch_access_token
          env:
            ID_TOKEN: $
          run: |
            ACCESS_TOKEN=$(curl \
            -X POST \
            -H "Content-type: application/json" \
            https://example.jfrog.io/access/api/v1/oidc/token \
            -d \
            "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"$ID_TOKEN\", \"provider_name\": \"YOUR_PROVIDER_NAME\"}" | jq .access_token | tr -d '"')
            echo ACCESS_TOKEN=$ACCESS_TOKEN >> $GITHUB_OUTPUT
